INSERT INTO movilidad (author,tipo_movilidad, actividad, descripcion_actividad, instituto, ciudad, modalidad, lugar, fecha_inicio, fecha_fin, tipo_author) 
VALUES 
/* Internacional */
('Elizabeth Ramírez Villamizar', 'Saliente', 'Semestre académico en el extrajero', 'Desarrollo de asignaturas', 'Universidad en el exterior', 'España', 'Presencial', 'Internacional', '', '', 'Estudiante'),
('Deiby Camilo Navarro Galvis','Saliente', 'Semestre académico en el extranjero', 'Desarrollo de asignaturas', 'Movilidad académica Colombia- Argentina (MACA) ASCUN-CIN Universidad Nacional de Catamarca', 'Argentina', 'Presencial', 'Internacional' , '', '' , 'Estudiante'),
('Edgar Jair Osorio Martínez', 'Saliente', 'Semestre Académico UFPS', 'Desarrollo de asignaturas', 'Benemérita Universidad Autónoma de Puebla', 'Mexico', 'Presencial', 'Internacional' , '', '' , 'Estudiante'),
('Amanda Xoxocatla Mar', 'Saliente', 'Semestre Académico UFPS', 'Desarrollo de asignaturas', 'Convenio Específico de Cooperación Interinstitucional de Movilidad Académica Colombia-México (MACMEX) ASCUN-ANUIES Instituto Tecnológico Superior de Poza Rica', 'Mexico', 'Presencial', 'Internacional' , '', '' , 'Estudiante'),
('Jesús Alberto Durán Juárez', 'Saliente', 'Semestre Académico UFPS', 'Desarrollo de asignaturas', 'Instituto Politécnico Nacional (IPN)', 'Mexico', 'Presencial', 'Internacional' , '', '' , 'Estudiante'),
('David Alejandro Tolosa Zabala', 'Saliente', 'Actividad de corta duración en el extranjero', 'Participación en la 4° Invernal Campamento de Programación Competitiva en Chile', 'Universidad Diego Portales', 'Chile', 'Presencial', 'Internacional' , '', '' , 'Estudiante'),
('José Manuel Salazar Meza', 'Saliente', 'Actividad de corta duración en el extranjero', 'Participación en la 4° Invernal Campamento de Programación Competitiva en Chile', 'Universidad Diego Portales', 'Chile', 'Presencial', 'Internacional' , '', '' , 'Estudiante'),
('Carlos Fernando Calderón Rivero', 'Saliente', 'Actividad de corta duración en el extranjero', 'Participación en la 4° Invernal Campamento de Programación Competitiva en Chile', 'Universidad Diego Portales', 'Chile', 'Presencial', 'Internacional' , '', '' , 'Estudiante'),
('Crisel Jazmín Ayala LLanes', 'Saliente', 'Actividad de corta duración en el extranjero', 'Participación en la 4° Invernal Campamento de Programación Competitiva en Chile', 'Universidad Diego Portales', 'Chile', 'Presencial', 'Internacional' , '', '' , 'Estudiante'),
('William Yesid Moreno Hernández', 'Saliente', 'Actividad de corta duración en el extranjero', 'Participación en la IX edición del evento Training Camp Argentina', 'Universidad de Buenos Aires', 'Argentina', 'Presencial', 'Internacional' , '', '' , 'Estudiante'),
('Brayan Fabián Godoy Ruíz', 'Saliente', 'Actividad de corta duración en el extranjero', 'Participación en la IX edición del evento Training Camp Argentina', 'Universidad de Buenos Aires', 'Argentina', 'Presencial', 'Internacional' , '', '' , 'Estudiante'),
('David Alejandro Tolosa Zabala', 'Saliente', 'Actividad de corta duración en el extranjero', 'Participación en la IX edición del evento Training Camp Argentina', 'Universidad de Buenos Aires', 'Argentina', 'Presencial', 'Internacional' , '', '' , 'Estudiante'),
('José Manuel Salazar Meza', 'Saliente', 'Actividad de corta duración en el extranjero', 'Participación en la IX edición del evento Training Camp Argentina', 'Universidad de Buenos Aires', 'Argentina', 'Presencial', 'Internacional' , '', '' , 'Estudiante'),
('Carlos Fernando Calderón Rivero', 'Saliente', 'Actividad de corta duración en el extranjero', 'Participación en la IX edición del evento Training Camp Argentina', 'Universidad de Buenos Aires', 'Argentina', 'Presencial', 'Internacional' , '', '' , 'Estudiante'),
('Crisel Jazmín Ayala LLanes', 'Saliente', 'Actividad de corta duración en el extranjero', 'Participación en la IX edición del evento Training Camp Argentina', 'Universidad de Buenos Aires', 'Argentina', 'Presencial', 'Internacional' , '', '' , 'Estudiante'),
('Edinsson Adrián Melo Calvo', 'Saliente', 'Semestre Académico en el extranjero', 'Desarrollo de asignaturas', 'Convenio de Intercambio Academico - Programa de Intercambio Académico Latinoamericano (PILA) ASCUN-ANUIES-CIN Universidad de Buenos Aires (UBA)', 'Argentina', 'Presencial', 'Internacional' , '', '' , 'Estudiante'),
('Elizabeth Ramírez Villamizar', 'Saliente', 'Actividad de corta duración en el extranjero', 'Asistencia a eventos', 'Fundación ICPC-Universidad de la Ciencias Informáticas', 'Cuba', 'Presencial', 'Internacional' , '', '' , 'Estudiante'),
('Brayan Sebastian Vega García', 'Saliente', 'Actividad de corta duración en el extranjero', 'Asistencia a eventos', 'Fundación ICPC-Universidad de la Ciencias Informáticas', 'Cuba', 'Presencial', 'Internacional' , '', '' , 'Estudiante'),
('José Manuel Salazar Mesa', 'Saliente', 'Actividad de corta duración en el extranjero', 'Asistencia a eventos', 'Fundación ICPC-Universidad de la Ciencias Informáticas', 'Cuba', 'Presencial', 'Internacional' , '', '' , 'Estudiante'),
('Cristian Leonardo Peñaranda Mora', 'Saliente', 'Semestre Académico en el extranjero', 'Desarrollo de asignaturas', 'Convenio Intercambio Académico Programa de Intercambio Académico Latinoamericano (PILA) ASCUN-ANUIES-CIN Universidad de Hipócrates', 'México', 'Presencial', 'Internacional' , '', '' , 'Estudiante'),
('Jairo Andrés Castañeda Pacheco', 'Saliente', 'Actividad de corta duración en el extranjero', 'Se planeo migrar una plataforma Moodle a la nube. La migración tuvo en cuenta la arquitectura de despliegue, el proveedor de nube, los aspectos críticos en seguridad y el impacto en los usuarios', 'REDCLARA', 'México', 'Presencial', 'Internacional' , '', '' , 'Estudiante'),

/* Nacional */
('José Manolo Pinzón Hernández', 'Saliente', 'Actividad de corta duración', 'Ponente (What?s massive aplicación web que implementa las API? De whatsapp para el envío de mensajería masiva) (modalidad póster)', 'Univerisidad de Santander (UDES) REDCOLSI', 'Valledupar', 'Presencial', 'Nacional', '7-10-2019', '12-10-2019' , 'Estudiante'),
('Nicola DiCandia Jaimes', 'Saliente', 'Actividad de corta duración', 'Ponente (Prototipo de un videojuego como estrategia para disminuir la depresión) Modalidad Poster', 'Univerisidad de Santander (UDES) REDCOLSI', 'Valledupar', 'Presencial', 'Nacional', '7-10-2019', '12-10-2019' , 'Estudiante'),
('Emanuel Martínez Pinzón', 'Saliente', 'Actividad de corta duración', 'Ponente (El semillero de investigación en inteligencia artificial (SIA) del programa de ingeniería de sistemas participará en el XXll encuentro nacional y XVl encuentro internacional de semilleros de investigación-fundación redcolsi con los siguientes proyectos: 
proyecto: Diseño, desarrollo e integración de un chatbot en organizaciones para la mejora en la atención al cliente usando inteligencia artificial como servicio en la nube.  Proyecto: Diseño de un videojuego activo para apoyar el tratamiento de la incapacidad de interacción social de individuos del espectro autista.', 'Univerisidad de Santander (UDES) REDCOLSI', 'Valledupar', 'Presencial', 'Nacional', '8-10-2019', '12-10-2019' , 'Estudiante'),
('Maria Alejandra Sosa Novoa', 'Saliente', 'Actividad de corta duración', 'Ponente (El semillero de investigación en inteligencia artificial (SIA) del programa de ingeniería de sistemas participará en el XXll encuentro nacional y XVl encuentro internacional de semilleros de investigación-fundación redcolsi con los siguientes proyectos: 
proyecto: Diseño, desarrollo e integración de un chatbot en organizaciones para la mejora en la atención al cliente usando inteligencia artificial como servicio en la nube.  Proyecto: Diseño de un videojuego activo para apoyar el tratamiento de la incapacidad de interacción social de individuos del espectro autista.', 'Univerisidad de Santander (UDES) REDCOLSI', 'Valledupar', 'Presencial', 'Nacional', '8-10-2019', '12-10-2019' , 'Estudiante'),
('Luis Ernesto Suárez', 'Saliente', 'Actividad de corta duración', 'Ponente del proyecto prototipo de un videojuego como apoyo en el proceso de enseñanza-aprendizaje de las tablas de multiplicar.', 'Univerisidad de Investigación y Desarrollo (UDI)', 'Bucaramanga', 'Presencial', 'Nacional', '22-10-2019', '23-10-2019' , 'Estudiante'),
('David Carreño Naranjo', 'Saliente', 'Actividad de corta duración', 'Ponente del proyecto prototipo de un videojuego como apoyo en el proceso de enseñanza-aprendizaje de las tablas de multiplicar.', 'Univerisidad de Investigación y Desarrollo (UDI)', 'Bucaramanga', 'Presencial', 'Nacional', '22-10-2019', '23-10-2019' , 'Estudiante'),
('Geimy Marcela Navarro Monsalve', 'Saliente', 'Actividad de corta duración', 'Ponente del proyecto prototipo de un videojuego como apoyo en el proceso de enseñanza-aprendizaje de las tablas de multiplicar.', 'Univerisidad de Investigación y Desarrollo (UDI)', 'Bucaramanga', 'Presencial', 'Nacional', '22-10-2019', '23-10-2019' , 'Estudiante'),
('Juliana Andrea Ortega Castillo', 'Saliente', 'Actividad de corta duración', 'Representar a la Universidad Francisco de Paula Santander en el lll campeonato nacional de cheer y performance cheer, colegial y equipos all stars, evento que se llevara a cabo en el centro de eventos y exposiciones de Bucaramanga.', 'Federación Colombiana de Porrismo', 'Bucaramanga', 'Presencial', 'Nacional', '8-11-2019', '11-11-2019' , 'Estudiante'),
('Carlos Fernando Calderón Rivero', 'Saliente', 'Actividad de corta duración', 'Competencia Regional Latinoamericana ICPC 2019-2020', 'Universidad Politécnico GranColombiano', 'Bogotá', 'Presencial', 'Nacional', '8-10-2019', '9-10-2019' , 'Estudiante'),
('Elizabeth Ramírez Villamizar', 'Saliente', 'Actividad de corta duración', 'Competencia Regional Latinoamericana ICPC 2019-2020', 'Universidad Politécnico GranColombiano', 'Bogotá', 'Presencial', 'Nacional', '8-10-2019', '9-10-2019' , 'Estudiante'),
('José Manuel Salazar Meza', 'Saliente', 'Actividad de corta duración', 'Competencia Regional Latinoamericana ICPC 2019-2020', 'Universidad Politécnico GranColombiano', 'Bogotá', 'Presencial', 'Nacional', '8-10-2019', '9-10-2019' , 'Estudiante'),
('Brayan Stevenson Arias Vargas', 'Saliente', 'Actividad de corta duración', 'Competencia Regional Latinoamericana ICPC 2019-2020', 'Universidad Politécnico GranColombiano', 'Bogotá', 'Presencial', 'Nacional', '8-10-2019', '9-10-2019' , 'Estudiante'),
('Crisel Jazmín Ayala LLanes', 'Saliente', 'Actividad de corta duración', 'Competencia Regional Latinoamericana ICPC 2019-2020', 'Universidad Politécnico GranColombiano', 'Bogotá', 'Presencial', 'Nacional', '8-10-2019', '9-10-2019' , 'Estudiante'),
('Angie Madeleyne Gonzales Barrera', 'Saliente', 'Actividad de corta duración', 'Competencia Regional Latinoamericana ICPC 2019-2020', 'Universidad Politécnico GranColombiano', 'Bogotá', 'Presencial', 'Nacional', '8-10-2019', '9-10-2019' , 'Estudiante'),


('Cristian Leonardo Peñaranda Mora', 'Saliente', 'Trabajo de grado en el extranjero', 'MVP funcional para solicitud y simulación de créditos en Chile', 'Zerftech LLC', 'Estados Unidos', 'Virtual', 'Internacional', '', '' , 'Estudiante');
